### ISSUE TITLE
TimeoutException when trying to check login credentials

### ISSUE THREAD

**Issue by PaulPerpetual** [fbuetler/asvz-bot#20]
I get the following error when trying to log in:

```
2023-03-02 12:23:23 INFO     Checking login credentials
Traceback (most recent call last):
  File "asvz_bot.py", line 606, in <module>
    main()
  File "asvz_bot.py", line 602, in main
    enroller.enroll()
  File "asvz_bot.py", line 261, in enroll
    self.__organisation_login(driver)
  File "asvz_bot.py", line 383, in __organisation_login
    WebDriverWait(driver, 20).until(
  File "~/asvz-bot/src/.venv/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
0   chromedriver                        0x0000000101338138 chromedriver + 4923704
1   chromedriver                        0x00000001012b09d3 chromedriver + 4368851
2   chromedriver                        0x0000000100ef9787 chromedriver + 472967
3   chromedriver                        0x0000000100f3dba3 chromedriver + 752547
4   chromedriver                        0x0000000100f3ddf1 chromedriver + 753137
5   chromedriver                        0x0000000100f84734 chromedriver + 1042228
6   chromedriver                        0x0000000100f66fdd chromedriver + 921565
7   chromedriver                        0x0000000100f81c0f chromedriver + 1031183
8   chromedriver                        0x0000000100f66d23 chromedriver + 920867
9   chromedriver                        0x0000000100f2da4b chromedriver + 686667
10  chromedriver                        0x0000000100f2f044 chromedriver + 692292
11  chromedriver                        0x00000001013038fe chromedriver + 4708606
12  chromedriver                        0x0000000101308e22 chromedriver + 4730402
13  chromedriver                        0x00000001013116bf chromedriver + 4765375
14  chromedriver                        0x0000000101309e80 chromedriver + 4734592
15  chromedriver                        0x00000001012da975 chromedriver + 4540789
16  chromedriver                        0x000000010132be78 chromedriver + 4873848
17  chromedriver                        0x000000010132bff5 chromedriver + 4874229
18  chromedriver                        0x00000001013406de chromedriver + 4957918
19  libsystem_pthread.dylib             0x00007ff80f4634e1 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff80f45ef6b thread_start + 15
```

Also after increasing the waiting time from 20sec to 120sec and using different internet connections the error persists. 

I use a Mac and switch to log in (UZH)

**Comment by PaulPerpetual** [comment]
The issue was that my chromium version was too new so there was not a corresponding chromedriver version
