### ISSUE TITLE
Multiple errors and AuthGuard warning

### ISSUE THREAD

**Issue by gogoloni** [fbuetler/asvz-bot#21]
I have the following errors and warnings when I run your code

```
2023-03-07 21:11:19 INFO     Checking login credentials

DevTools listening on ws://127.0.0.1:50939/devtools/browser/f201eec3-147e-4e74-a12f-200b637adc1c
[0307/211120.770:INFO:CONSOLE(1)] "WARNING: AuthGuard should be implemented for this route:  https://schalter.asvz.ch/tn/lessons/434778", source: https://schalter.asvz.ch/tn/main.0d96478c7988d889.js (1)
[0307/211120.776:INFO:CONSOLE(1)] "ERROR [object Object]", source: https://schalter.asvz.ch/tn/main.0d96478c7988d889.js (1)
[0307/211120.776:INFO:CONSOLE(1)] "ERROR [object Object]", source: https://schalter.asvz.ch/tn/main.0d96478c7988d889.js (1)
2023-03-07 21:11:22 INFO     Login to 'ETH Zürich'
2023-03-07 21:11:23 INFO     Submitted login credentials
2023-03-07 21:12:02 INFO     Valid login credentials
[0307/211203.895:INFO:CONSOLE(1)] "WARNING: AuthGuard should be implemented for this route:  https://schalter.asvz.ch/tn/lessons/434778", source: https://schalter.asvz.ch/tn/main.0d96478c7988d889.js (1)
[0307/211203.895:INFO:CONSOLE(1)] "ERROR [object Object]", source: https://schalter.asvz.ch/tn/main.0d96478c7988d889.js (1)
2023-03-07 21:12:08 ERROR    Element on website not found! This may happen when the website was updated recently. Please report this incident to: https://github.com/fbuetler/asvz-bot/issues
2023-03-07 21:12:08 ERROR    Element on website not found! This may happen when the website was updated recently. Please report this incident to: https://github.com/fbuetler/asvz-bot/issues
Traceback (most recent call last):
  File "C:\Users\lorin\OneDrive\Dokumente\ETH\Sonstiges\asvz_bot\asvz_bot.py", line 605, in <module>
    main()
  File "C:\Users\lorin\OneDrive\Dokumente\ETH\Sonstiges\asvz_bot\asvz_bot.py", line 601, in main
    enroller.enroll()
  File "C:\Users\lorin\OneDrive\Dokumente\ETH\Sonstiges\asvz_bot\asvz_bot.py", line 267, in enroll
    raise e
  File "C:\Users\lorin\OneDrive\Dokumente\ETH\Sonstiges\asvz_bot\asvz_bot.py", line 264, in enroll
    ) = AsvzEnroller.__get_enrollment_and_start_time(driver)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lorin\OneDrive\Dokumente\ETH\Sonstiges\asvz_bot\asvz_bot.py", line 336, in __get_enrollment_and_start_time
    raise e
  File "C:\Users\lorin\OneDrive\Dokumente\ETH\Sonstiges\asvz_bot\asvz_bot.py", line 332, in __get_enrollment_and_start_time
    enrollment_start = AsvzEnroller.__get_enrollment_time(driver)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lorin\OneDrive\Dokumente\ETH\Sonstiges\asvz_bot\asvz_bot.py", line 342, in __get_enrollment_time
    enrollment_interval_raw = driver.find_element(
                              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lorin\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 830, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lorin\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\lorin\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//dl[contains(., 'Einschreibezeitraum')]/dd"}
  (Session info: headless chrome=110.0.5481.178)
Stacktrace:
Backtrace:
        (No symbol) [0x004337D3]
        (No symbol) [0x003C8B81]
        (No symbol) [0x002CB36D]
        (No symbol) [0x002FD382]
        (No symbol) [0x002FD4BB]
        (No symbol) [0x00333302]
        (No symbol) [0x0031B464]
        (No symbol) [0x00331215]
        (No symbol) [0x0031B216]
        (No symbol) [0x002F0D97]
        (No symbol) [0x002F253D]
        GetHandleVerifier [0x006AABF2+2510930]
        GetHandleVerifier [0x006D8EC1+2700065]
        GetHandleVerifier [0x006DC86C+2714828]
        GetHandleVerifier [0x004E3480+645344]
        (No symbol) [0x003D0FD2]
        (No symbol) [0x003D6C68]
        (No symbol) [0x003D6D4B]
        (No symbol) [0x003E0D6B]
        BaseThreadInitThunk [0x76757D69+25]
        RtlInitializeExceptionChain [0x7755BB9B+107]
        RtlClearBits [0x7755BB1F+191]
```

Any chance you can help me sort this out?

Thanks for this lovely idea of a script by the way :)

**Comment by fbuetler** [comment]
It looks like the ASVZ website has in general some issues currently. I am going to look into it again later this week.

**Comment by fbuetler** [comment]
I used the most recent version of the script yesterday, and it worked fine. So maybe this was a temporal issue?

**Comment by aledecc** [comment]
I am having the same issues. Tried it just now.

**Comment by fbuetler** [comment]
You can delete the following line to see what the script is doing:

```python
options.add_argument("--headless")
```

On https://github.com/fbuetler/asvz-bot/blob/master/src/asvz_bot.py#L210

Maybe that helps ;)

**Comment by aledecc** [comment]
Okay I figured it out. Turns out that the username and password differ from the generic SWITCHaai one. Had to use my full @uzh.ch username and a different password in order to log in. Didn't realise I had an account just for ASVZ.
Works like a charm now :)

**Comment by fbuetler** [comment]
Awesome!
