### ISSUE TITLE
2FA causing problems (?)

### ISSUE THREAD

**Issue by lu-fr** [fbuetler/asvz-bot#26]
Thanks for this useful tool! ;)

I am having issues with using it, due to the newly added 2FA. If I run the script with 

`python3 asvz_bot.py --organisation "UZH" --username "username" --save-credentials lesson lessonID`

I receive the text message from SWITCHsms for 2FA on my phone and the output below. Are there any solutions (planned) to be able to use the tool even with the enforced 2FA?

```
2023-04-25 14:24:49 INFO     Checking login credentials
2023-04-25 14:24:51 INFO     Login to 'Universität Zürich'
2023-04-25 14:24:56 INFO     Submitted login credentials
2023-04-25 14:24:59 WARNING  Authentication might have failed. Current URL is 'https://uzh.login.eduid.ch/idp/profile/SAML2/Redirect/SSO?execution=e1s3'
2023-04-25 14:25:05 ERROR    Element on website not found! This may happen when the website was updated recently. Please report this incident to: https://github.com/fbuetler/asvz-bot/issues
2023-04-25 14:25:05 ERROR    Element on website not found! This may happen when the website was updated recently. Please report this incident to: https://github.com/fbuetler/asvz-bot/issues
Traceback (most recent call last):
  File "asvz_bot.py", line 610, in <module>
    main()
  File "asvz_bot.py", line 606, in main
    enroller.enroll()
  File "asvz_bot.py", line 272, in enroll
    raise e
  File "asvz_bot.py", line 269, in enroll
    ) = AsvzEnroller.__get_enrollment_and_start_time(driver)
  File "asvz_bot.py", line 341, in __get_enrollment_and_start_time
    raise e
  File "asvz_bot.py", line 337, in __get_enrollment_and_start_time
    enrollment_start = AsvzEnroller.__get_enrollment_time(driver)
  File "asvz_bot.py", line 347, in __get_enrollment_time
    enrollment_interval_raw = driver.find_element(
  File "/home/lufr/asvz-bot-master/src/.venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 830, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/home/lufr/asvz-bot-master/src/.venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/home/lufr/asvz-bot-master/src/.venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//dl[contains(., 'Einschreibezeitraum')]/dd"}
  (Session info: headless chrome=112.0.5615.165)
Stacktrace:
#0 0x562afc06efe3 <unknown>
#1 0x562afbdadd36 <unknown>
#2 0x562afbdeac4d <unknown>
#3 0x562afbdead61 <unknown>
#4 0x562afbe266a4 <unknown>
#5 0x562afbe0b8ed <unknown>
#6 0x562afbe24232 <unknown>
#7 0x562afbe0b693 <unknown>
#8 0x562afbdde03a <unknown>
#9 0x562afbddf17e <unknown>
#10 0x562afc030dbd <unknown>
#11 0x562afc034c6c <unknown>
#12 0x562afc03e4b0 <unknown>
#13 0x562afc035d63 <unknown>
#14 0x562afc008c35 <unknown>
#15 0x562afc059138 <unknown>
#16 0x562afc0592c7 <unknown>
#17 0x562afc067093 <unknown>
#18 0x7fefdaef2609 start_thread
```

**Comment by fbuetler** [comment]
You can use the ASVZ login.

**Comment by lu-fr** [comment]
Seems like a super easy fix - however as far as I know (UZH) students don't have an ASVZ-ID (since they can use SwitchAAI login).

**Comment by fbuetler** [comment]
You can create yourself an ASVZ ID by visiting https://auth.asvz.ch/account/login, choosing "forgot password" in the ASVZ ID component and then either entering your UZH email address or your ASVZ ID (can be found in the ASVZ account, when you are logged in with SwitchAAI).

**Comment by lu-fr** [comment]
I couldn't find it anywhere in my ASVZ account info. But with the "forgot password" option I received an email from ASVZ with my ASVZ-ID, and managed to enroll using this login. Thanks for your help!
